version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/database:/app/database
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
    command: flask run --host=0.0.0.0

  myapp:
    build:
      context: ./client/MyApp
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./client/MyApp:/app
    depends_on:
      - backend
